CONNECT TO COMP421;

--#SET TERMINATOR #
CREATE OR REPLACE PROCEDURE check_like (IN userid_in INTEGER)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
P: BEGIN
	DECLARE tempuid INTEGER;
	DECLARE temppid INTEGER;
	DECLARE at_end INTEGER DEFAULT 0;
	DECLARE not_found CONDITION FOR SQLSTATE='02000';
	DECLARE cursor1 CURSOR FOR
		SELECT userid, postid FROM Likes WHERE userid=userid_in;
	DECLARE CONTINUE HANDLER FOR not_found SET at_end=1;
	OPEN cursor1;
	FETCH cursor1 INTO tempuid, temppid;
	WHILE at_end=0 DO
END P#
